server:
  port: 8081

spring:
  application:
    name: cart-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cartdb
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    register-with-eureka: true  # Đăng ký service này với Eureka
    fetch-registry: true  # Lấy danh sách các service từ Eureka
    service-url:
      defaultZone: http://localhost:8761/eureka/
